# Generated by Django 4.1.7 on 2023-07-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showdid',
        ),
    ]
